# Generated by Django 4.1.4 on 2023-01-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('picture', models.URLField()),
                ('age', models.IntegerField()),
                ('eyeColor', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.BooleanField(choices=[(0, 'male'), (1, 'female')])),
                ('company', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('about', models.TextField()),
                ('registered', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('greetings', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='profile_app.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profile_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='profile_app.profile')),
            ],
        ),
    ]
