# Generated by Django 4.1.4 on 2023-01-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_profile_balance_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
