# Generated by Django 4.1.4 on 2023-01-02 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_alter_profile_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
